version: "3.9"

services:
  web:
    build: .
    container_name: ouchi-face
    ports:
      - "8000:8000"
    environment:
      - OUCHI_FACE_DB_PATH=/data/ouchi_face.db
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data:
    driver: local
